# -*- coding: utf-8 -*-
"""LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19i0JZPX1Ldr3M1cnNg9IZAwkoRULfwIl
"""

import gdown
import pandas as pd
import numpy as np
import re
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional

# Téléchargement du dataset
url = "https://drive.google.com/uc?id=1vnf0SL2ucnABzL5nWUbZRvyto8rS2rMz"
output = "imdb.csv"
gdown.download(url, output, quiet=False)

# Fonction pour nettoyer les données textuelles
def clean_data(text):
    text = text.lower()
    text = re.sub(r'<.*?>', '', text)  # Supprimer les balises HTML
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # Supprimer les caractères non alphabétiques
    text = re.sub(r'\s+', ' ', text)  # Supprimer les espaces multiples
    return text.strip()

# Chargement des données
data = pd.read_csv("imdb.csv")
data['review'] = data['review'].apply(clean_data)

# Encodage des labels
label_encoder = LabelEncoder()
data['sentiment'] = label_encoder.fit_transform(data['sentiment'])  # "positive" -> 1, "negative" -> 0

# Préparation des données pour le modèle
max_vocab_size = 10000  # Limite du nombre de mots dans le vocabulaire
max_seq_length = 200    # Longueur maximale des séquences

tokenizer = Tokenizer(num_words=max_vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(data['review'])
sequences = tokenizer.texts_to_sequences(data['review'])
padded_sequences = pad_sequences(sequences, maxlen=max_seq_length, padding='post', truncating='post')

# Division en ensembles d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(
    padded_sequences, data['sentiment'], test_size=0.2, random_state=42
)

# Création du modèle LSTM
embedding_dim = 64

model = Sequential([
    Embedding(input_dim=max_vocab_size, output_dim=embedding_dim, input_length=max_seq_length),
    Bidirectional(LSTM(64, return_sequences=True)),
    Dropout(0.5),
    Bidirectional(LSTM(32)),
    Dense(64, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')  # Sigmoid pour une classification binaire
])

# Compilation du modèle
model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

# Résumé du modèle
print(model.summary())

# Entraînement du modèle
num_epochs = 5
batch_size = 32

history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=num_epochs,
    batch_size=batch_size,
    verbose=1
)

# Évaluation finale
loss, accuracy = model.evaluate(X_test, y_test, verbose=1)
print(f"Précision sur l'ensemble de test : {accuracy:.2f}")

